### ISSUE TITLE
Lumafix possibility?

### ISSUE THREAD

**Issue by Hojo-Norem** [c0pperdragon/C64-Video-Enhancement#21]
I've seen a few comments online from some people who have mistakenly deduced that the mod disables the C64's composite and Y/C outputs.  That got me thinking, could the LumaFix64 circuit be added to the VIC-II board?  Using single gate ICs would mean that the only real work would be making room for the trimpots.  I might DL Kicad and give it a go myself.

While there's more real estate on the main PCB, I'm guessing that the skew between the relevant bus signals and the VIC-II's output may be large that the LumaFix circuit may not operate as effectively.

**Comment by c0pperdragon** [comment]
When I designed the board, I did not give this issue so much thoughts. After all, the mod is there to replace the analog signal altogether. Providing the original A/V signal was more a means of doing a side-by side comparison to check for compatibility.

Anyway, replicating the LumaFix64 functionality would need to be done on the VIC adapter board, 
because the digital signals pass through an additional logic gate before reaching the FPGA board, so they may be late to properly cancel out the various signal artifacts.

But the adapter board is pretty small and quite crowded already. 

One possibility is to just add the original LumaFix64 to the stack under the VIC. This would work for sure from an electronic point of view, but the stack gets really high then any may not fit into the case, especially when having a heatsink on the VIC. 
Matt from videogameperfection.com actually claims compatibility, but I am not sure if this is really such a usable option.
