### ISSUE TITLE
Glitches/Interference with analog only board.

### ISSUE THREAD

**Issue by eflopez** [c0pperdragon/C64-Video-Enhancement#41]
I put together a couple of the analog only boards but they both end up with glitchy video. On one, I get good video for about 20-30 seconds and then it starts to have these issues. The other board is no good pretty much straight away. They both exhibit the same artefacts though.

I don't have a lot experience with electronics, so wondering if I've done something wrong, and not sure how to investigate further. 

This is for a PAL 250469 (No. 252311 REV.4) shortboard with composite video on a CRT TV.

Any ideas?

![IMG_8136](https://user-images.githubusercontent.com/22426865/90620734-3146a680-e256-11ea-8a25-79806b8809c6.JPG)
![IMG_8137](https://user-images.githubusercontent.com/22426865/90620738-34da2d80-e256-11ea-9644-9d4251584699.JPG)

**Comment by c0pperdragon** [comment]
If you are referring to this diagonal stripe of light and the neighbouring vertical strip, I would really have not the slightest idea. But I guess this is just a reflection from your room, door  isn't it?

But I don't know where the rest of the noise comes from. The whole analog signal path of the VIC is pretty bad already, and composite video even more so. The analog video board can not really do much about this. But maybe there is something specificly wrong with your installation. Please make a picture of your install, so I could better guess what is going on.

**Comment by eflopez** [comment]
Yep, diagonal line and vertical strip are just a reflection from the window :)

I've uploaded some photos and a video here:
https://drive.google.com/drive/folders/1gSFHNOk5FvQe_4_FEl2io-MgXK0Rk7pV

You can see the noise start at about 14 seconds, before that the output looks quite good.
Since it works well for a bit, my hunch is that as some component warms up, it starts to cause problems.

Please excuse my poor soldering, first time doing SMD. 

I did have to substitute the LM1117 which wasn't in stock locally with a TLV1117 which according to the LM1117 datasheet is s drop in replacement could this be the problem?

FWIW I don't think its the 64 board, as this doesn't happen with [another video bypass circuit](https://github.com/mbarszcz-pcb/c64-rf-modulator-replacement). The output of that one is good, but theres a lot of chroma bleed, more than the original modulator.

**Comment by c0pperdragon** [comment]
The regulator you are using as very similar specs to my original one. Maybe a very slighly higher drop-out voltage, which could actualy worsen the effect of voltage ripple on the 5V supply line. With a 1.3 drop-out the margin between 5V and 3.3V is already nearly exhausted further degradation will probably show.

The horizontal distance of the vertical noise bands looks like it is caused by some supply voltage ripple of about 100kHz.  This hints at a switching power supply with insufficient ripple suppression. 
That the effect starts only after some time may be caused by the PSU heating up. 
Do you have an oscillator to probe the 5V line (rightmost pin on your board) to verify this? 

Looking at the schematics of your main board, there is the filter capacitor C58 that should already reduce incomming ripple. Maybe this has gone bad already or just is not up to the taks with your PSU. You could try to replace this with a newer and higher-capacitance piece. 470uF could probably improve the matter.

**Comment by c0pperdragon** [comment]
oops - of course I meant "oscilloscope", not "oscillator"

**Comment by eflopez** [comment]
Unfortunately I don't have an oscilloscope, so I can't check this out. I do have is the original c64c 2A epoxy brick power supply, and the older black 1A one from a breadbin, and both have the same issue. C58 looks ok visually, I'll have to order more parts to replace it though.

I kludged together an s-video cable to an old LCD TV just in case it was composite. Same story. On the plus side s-video looks fantastic if it wasn't for the interference / noise.

I'll try and build another one from scratch and pay extra attention to not overheat any components.

**Comment by c0pperdragon** [comment]
So maybe it is indeed a trouble with your TLV1117 after all, as this is the only thing that is in any way different from my original design, which is already pretty well tested by many users.

**Comment by c0pperdragon** [comment]
First hit when searching google for "TLV1117 noise":  https://e2e.ti.com/support/power-management/f/196/t/99360?TLV1117-noise

**Comment by eflopez** [comment]
Damn :( lesson learnt. I'll wait until they are in stock again locally and order the proper one. 
Thanks so much for you help!

**Comment by eflopez** [comment]
Hey, I replaced the regulator with the LM1117 and things are working amazingly! Composite looks great too.
