### ISSUE TITLE
Graphics glitches in Edge of disgrace

### ISSUE THREAD

**Issue by sivu** [c0pperdragon/C64-Video-Enhancement#50]
In [Edge of disgrace](https://csdb.dk/release/?id=72550) there are couple of places where some pixels that are not behaving as they should, usually in the top or bottom left of the effect.

example from around [this part](https://youtu.be/nLIUkBa_mA0?t=66)
![IMG_1713](https://user-images.githubusercontent.com/348411/97544635-8f200900-19d2-11eb-81bd-004a5102e3fe.png)

I am running 2.9 firmware.

**Comment by c0pperdragon** [comment]
I know that this Demo actually has some real glitches which are also visible on the original s-video/composite output. 
These often happen in the various border regions and are sometimes not visible on analog screens because they are too far in the overscan region or too faint to be propperly perceived. As far as I know, the mod board truthfully reproduces all of those glitches. If you have a way to capture/view the original analog video alongside the mod output, please try to make such a direct comparison.

**Comment by sivu** [comment]
Yeah, I will try to capture the comparison. I think I also saw some glitchy pixels further away from the border, I will try to capture those too.

**Comment by sivu** [comment]
Compared to svideo out and same issues are seen so closing this
