### ISSUE TITLE
Need help with FPGA Mod + external RGB2HDMI

### ISSUE THREAD

**Issue by lolof70** [c0pperdragon/C64-Video-Enhancement#73]
Hi,

I do not know if I have to post this here or to the rgb2hdmi page..
I am trying here. I just added the external RGB2HDMI to the FPGA mod in a C64.
FPGA mod is working perfectly...
I have problem with the RGB2HDMI mod :-(
See the pictures. Colours are not good. I have the last version on the FPGA board. So I did not had to programm the C64 palette.. I put a bridge on the pin 9&10 from the fpga jtag connector. The switch is on the right side (facing the C64).
My cable seems to be OK, I checked it again now..

I am afraid it could be a problem with the analog board issue 3... I do not know where to look.

All parts of the analog Board are from Mouser except the MAX5259+ (not available. Found @ ebay china
D1 is not the one from the bom, not available. I took another one 

https://www.mouser.de/api/CrossDomain/SetContext?qs=bBn1FhEllS9U0dDp%2f71pOPiUJe3tZ6Ip1ZMh3OE2nv0xUzF%2fMuylote9ddp3rOYYukiihePXlcDfag7OjsvTE9Upa0FNsRpkpRGisA8gBCj1r0jQkZNiQeZi1b8vHpd5bz32F3qdT90y4S4tI8U0LCjUVemRndietnon4CL8ld1A5L7yaCdPGXMX%2fSLNpuxov17YS2IDKYUPVMQolWxU%252BT5T2sK6MSD8CpvijeuUHnKalKVlkhdBx6kG0HXwNonc&syncDomain=de&async=False

Could someone help me. Thank you.

![1635874994527](https://user-images.githubusercontent.com/39760189/139918372-d3e21499-8a4a-4636-a71e-19b145a1bf43.jpg)
![1635875015586](https://user-images.githubusercontent.com/39760189/139918388-e94a6e5c-e712-413f-a22e-8aec4053250d.jpg)
![1635873490642](https://user-images.githubusercontent.com/39760189/139918438-4a436708-ae31-4bc8-a7e6-f79004b79d3f.jpg)
![1635873490632](https://user-images.githubusercontent.com/39760189/139918458-c4dce273-5f43-4b92-b6ce-68c8a8586b5b.jpg)

**Comment by c0pperdragon** [comment]
When the mod board gives correct colors in normal operation (no jumper), then it is very unlikely that this is the problem.
So the issue is either with the cabling (if you are lucky) or with the analog board (unlucky) or it is just a matter of correctly calibrating the input voltage levels (extremely lucky). 
Try playing with the rgb2hdmi settings first and see if you can make the board discriminate 3 different input levels on each of the signal components (Y, Pb, Pr). The sync already is detected perfectly. 
I don't remember how to use the settings menu of the RGB2HDMI but after pressing the button, you should be able to guess your way through the menu.

**Comment by lolof70** [comment]
It's like it's missing red and blue colours... I saw yellow, black, braun,....
I re-checked the cable. I do not see a mistake...
I changed the only parts coming from ebay china with another from the lot I bought, just in case... Same result.
I went in Menu and tried to change what I could, like contarst etc....  Does not help.
I also connect all on another monitor. Same....

How do I calibrate the output voltage ? I did another board, digital for C128 and this one worked directly with default setting on the same monitor...

**Comment by lolof70** [comment]
Just found an error I did on the analog board......
Maybe it's the problem.

R1 should be 470 ohm... I do not know why, I put a 100 ohm one....

PS : hummmm, on the wiki in the BOM it says 470 Ohm.... On the kicad BOM, it says 100.....

I will post some questions on the rgb2hdmi github  because there is more than one thing not corresponding from the wiki bom  and the Kicad one.... 

Thank you for all.

**Comment by lolof70** [comment]
Tried with R1 470 Ohm on the analog board. No difference...

A last question, on my FPGA board, I replace R18 and R19 by 75 Ohm, should I put the original value one ?
Can this be a problem ?

I also put my cable connection here just in case......  If I well understood the wiki, this should be correctly connected...

![1635931437234](https://user-images.githubusercontent.com/39760189/140038375-50e3b318-593b-4861-bdad-809bac4ee423.jpg)

**Comment by c0pperdragon** [comment]
Yes, this would definitely make a difference. With this lower-value resistors the output levels for Pb ad Pr would be muhc lower. This would lead to less saturated colors when used with a normal YPbPr-enabled TV. But due to the the way the RGB2HDMI reads the analog signals, whis would very likely cause the input to be incorrectly interpreted when using the default settings. 
So either replace the resistors again or reconfigure the input voltage levels for the red and blue lines using the RGB2HDMI's settings menu.

**Comment by c0pperdragon** [comment]
Have a look at
https://github.com/hoglet67/RGBtoHDMI/wiki/Reference-Guide
in the section Sampling Menu (6 BIT RGB analog inputs)
This is where you can reconfigure the analog voltage levels.

**Comment by lolof70** [comment]
Problem fixed...

Yes, it was only the 2 resistors I replaced on the fpga board. I just put the original value back on the PCB and now, all is working perfectly !

Thank you for all.
